### ISSUE TITLE
Syntax error on mysql install script

### ISSUE THREAD

**Issue by bhargav-nunna** [aws-samples/aws-database-migration-samples#12]
I get the following error when I try to install DB using install-rds.sql:

ERROR 1064 (42000) at line 648 in file: './data/name_data.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Insert into name_data (name_type,name) values ('MALE_FIRST','Agustin')' at line 2
Operation failed with exitcode 1

I am using MySQL workbench to run the script and my database is 
db.m4.large RDS instance with MySQL engine version 5.7.22. Please look into this issue. Thanks in advance.

**Comment by ryanjmich** [comment]
Missing semicolon after previous insert statement. Checked in change.
